/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

/**
 *
 * @author sandr
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoOpciones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JToggleButton();
        btnListado = new javax.swing.JToggleButton();
        btnEdicion = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        btnComparacion = new javax.swing.JToggleButton();
        btnOrdenamiento = new javax.swing.JToggleButton();
        contenedorOpc = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grupoOpciones.add(btnRegistro);
        btnRegistro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistro.setText("Registro de eventos");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        grupoOpciones.add(btnListado);
        btnListado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnListado.setText("Listado de eventos");
        btnListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoActionPerformed(evt);
            }
        });

        grupoOpciones.add(btnEdicion);
        btnEdicion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEdicion.setText("Búsqueda /Edicion de eventos");
        btnEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdicionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MS Gothic", 2, 24)); // NOI18N
        jLabel1.setText("Eventos");

        grupoOpciones.add(btnComparacion);
        btnComparacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnComparacion.setText("Comparación de valores");
        btnComparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComparacionActionPerformed(evt);
            }
        });

        grupoOpciones.add(btnOrdenamiento);
        btnOrdenamiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnOrdenamiento.setText("Ordenamiento lista eventos deportivos");
        btnOrdenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(119, 119, 119))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListado, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnListado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnComparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout contenedorOpcLayout = new javax.swing.GroupLayout(contenedorOpc);
        contenedorOpc.setLayout(contenedorOpcLayout);
        contenedorOpcLayout.setHorizontalGroup(
            contenedorOpcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 933, Short.MAX_VALUE)
        );
        contenedorOpcLayout.setVerticalGroup(
            contenedorOpcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorOpc)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedorOpc)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    RegistroEventosFrame registro;
    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        if (registro == null) {

            //Se inicailiza la ventana de registro
            registro = new RegistroEventosFrame();

            // Se agrega la ventana de registro al contenedor y se maximiza
            contenedorOpc.getDesktopManager().maximizeFrame(registro);
            
            //Se agrega regsitro al contenedorOpc
            contenedorOpc.add(registro);
            
            //Se le da indica que registro sea visible
            registro.setVisible(true);
        } else {
            // Si la ventana de registro ya está abierta solo se maximiza
            contenedorOpc.getDesktopManager().maximizeFrame(registro);
        }
    }//GEN-LAST:event_btnRegistroActionPerformed

    BusquedaYEdicionDeEventosFrame busquedaYedicion;
    private void btnEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdicionActionPerformed
        //Se verifica si ya existe una ventana de busquedaYedicion
        if (busquedaYedicion == null) {
            //Se inicailiza la ventana de busqueda y edicion
            busquedaYedicion = new BusquedaYEdicionDeEventosFrame();
            contenedorOpc.getDesktopManager().maximizeFrame(busquedaYedicion);
            contenedorOpc.add(busquedaYedicion);
            busquedaYedicion.setVisible(true);
        } else {
            contenedorOpc.getDesktopManager().maximizeFrame(busquedaYedicion);
        }
    }//GEN-LAST:event_btnEdicionActionPerformed

    private void btnComparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComparacionActionPerformed
        //Se crea y iniciailiza la ventana de comparacion
        ComparacionDeValoresFrame comparacion = new ComparacionDeValoresFrame();
        contenedorOpc.getDesktopManager().maximizeFrame(comparacion);
        contenedorOpc.add(comparacion);
        comparacion.setVisible(true);
    }//GEN-LAST:event_btnComparacionActionPerformed

    ListadoEventosFrame listado;
    private void btnListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoActionPerformed
       //Se crea y iniciailiza la ventana de listado de Eventos
        ListadoEventosFrame listado = new ListadoEventosFrame();
        contenedorOpc.getDesktopManager().maximizeFrame(listado);
        contenedorOpc.add(listado);
        listado.setVisible(true);

    }//GEN-LAST:event_btnListadoActionPerformed


    private void btnOrdenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenamientoActionPerformed
        //Se crea y iniciailiza la ventana de ordenamiento
        OrdenamientoListadosDeportivosFrame ordenamiento = new OrdenamientoListadosDeportivosFrame();
        contenedorOpc.getDesktopManager().maximizeFrame(ordenamiento);
        contenedorOpc.add(ordenamiento);
        ordenamiento.setVisible(true);

    }//GEN-LAST:event_btnOrdenamientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnComparacion;
    private javax.swing.JToggleButton btnEdicion;
    private javax.swing.JToggleButton btnListado;
    private javax.swing.JToggleButton btnOrdenamiento;
    private javax.swing.JToggleButton btnRegistro;
    private javax.swing.JDesktopPane contenedorOpc;
    private javax.swing.ButtonGroup grupoOpciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
